### ISSUE TITLE
Dynamically change Shuttle Schedule strings according to System Language

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#133] opened 2020-03-02 00:27 UTC
Users will have an adaptive language option on the Shuttle Schedule which stays in tune with the default System Language setting.

**Comment by vicmanea** [comment] 2020-03-02 00:37
Acceptance criteria:

- [ ] : The Shuttle Schedule text is adaptive to system settings

**Comment by JenYn** [comment] 2020-03-31 20:21
This is a duplicate of issue #18. We will therefore close it.

**Closed by JenYn** 2020-03-31 20:21 UTC
Labels: Superfluous, duplicate
