### ISSUE TITLE
Dynamically change Building Info strings according to System Language

### ISSUE THREAD

**Issue by vicmanea** [jaychenblue/scout-concordia#136] opened 2020-03-02 00:33 UTC
Users will have an adaptive language option on the Building Info, which stays in tune with the default System Language setting.

**Comment by vicmanea** [comment] 2020-03-02 00:37
Acceptance criteria:

- [ ] : The Building Info text is adaptive to system settings

**Comment by jaychenblue** [comment] 2020-03-14 03:28
I'm not quite sure what the purpose of this issue is. Can you elaborate?

**Comment by vicmanea** [comment] 2020-03-14 18:12
This was originally an extension of the language-switching feature, as I figured that every person would be in charge of implementing it into their own component.

**Comment by JenYn** [comment] 2020-03-31 20:21
This is a duplicate of issue #18. We will therefore close it.

**Closed by JenYn** 2020-03-31 20:21 UTC
Labels: Superfluous, duplicate
